const X_AXIS_UNIT_MONTHS = 'Months';
const X_AXIS_UNIT_QUARTERS = 'Quarters';
const X_AXIS_UNIT_YEARS = 'Years';
const X_AXIS_UNIT_OPTIONS = [{
		value: X_AXIS_UNIT_MONTHS,
		label: X_AXIS_UNIT_MONTHS
	}, {
		value: X_AXIS_UNIT_QUARTERS,
		label: X_AXIS_UNIT_QUARTERS
	}, {
		value: X_AXIS_UNIT_YEARS,
		label: X_AXIS_UNIT_YEARS
	}
];
const X_AXIS_UNITS = X_AXIS_UNIT_OPTIONS.map((e) => {
	return e.value;
});

const DATA_SERIES_TYPE_BAR_POSITIVE = 'bar+';
const DATA_SERIES_TYPE_BAR_NEGATIVE = 'bar-';
const DATA_SERIES_TYPE_LINE_POSITIVE = 'line+';
const DATA_SERIES_TYPE_LINE_NEGATIVE = 'line-';
const DATA_SERIES_TYPE_SPLINE_POSITIVE = 'spline+';
const DATA_SERIES_TYPE_SPLINE_NEGATIVE = 'spline-';
const DATA_SERIES_TYPE_OPTIONS = [{
		value: DATA_SERIES_TYPE_BAR_POSITIVE,
		label: 'Bar positive'
	}, {
		value: DATA_SERIES_TYPE_BAR_NEGATIVE,
		label: 'Bar negative'
	}, {
		value: DATA_SERIES_TYPE_LINE_POSITIVE,
		label: 'Line positive'
	}, {
		value: DATA_SERIES_TYPE_LINE_NEGATIVE,
		label: 'Line negative'
	}, {
		value: DATA_SERIES_TYPE_SPLINE_POSITIVE,
		label: 'Spline positive'
	}, {
		value: DATA_SERIES_TYPE_SPLINE_NEGATIVE,
		label: 'Spline negative'
	}
];
const DATA_SERIES_TYPES = DATA_SERIES_TYPE_OPTIONS.map((e) => {
	return e.value;
});

const DATA_SERIES_STACK_LAST = 'last';
const DATA_SERIES_STACK_FIRST = 'first';
const DATA_SERIES_STACK_EVERY = 'every';
const DATA_SERIES_STACK_OPTIONS = [{
		value: DATA_SERIES_STACK_LAST,
		label: 'Only last occurrence'
	}, {
		value: DATA_SERIES_STACK_FIRST,
		label: 'Only first occurrence'
	}, {
		value: DATA_SERIES_STACK_EVERY,
		label: 'Every occurrence'
	}
];
const DATA_SERIES_STACKS = DATA_SERIES_STACK_OPTIONS.map((e) => {
	return e.value;
});

const DATA_SERIES_AXIS_Y = 'y';
const DATA_SERIES_AXIS_Y2 = 'y2';
const DATA_SERIES_AXIS_OPTIONS = [{
		value: DATA_SERIES_AXIS_Y,
		label: 'Y'
	}, {
		value: DATA_SERIES_AXIS_Y2,
		label: 'Y2'
	}
];
const DATA_SERIES_AXES = DATA_SERIES_AXIS_OPTIONS.map((e) => {
	return e.value;
});

export default {
	X_AXIS_UNIT_MONTHS: X_AXIS_UNIT_MONTHS,
	X_AXIS_UNIT_QUARTERS: X_AXIS_UNIT_QUARTERS,
	X_AXIS_UNIT_YEARS: X_AXIS_UNIT_YEARS,
	X_AXIS_UNIT_OPTIONS: X_AXIS_UNIT_OPTIONS,
	X_AXIS_UNITS: X_AXIS_UNITS,
	DATA_SERIES_TYPE_BAR_POSITIVE: DATA_SERIES_TYPE_BAR_POSITIVE,
	DATA_SERIES_TYPE_BAR_NEGATIVE: DATA_SERIES_TYPE_BAR_NEGATIVE,
	DATA_SERIES_TYPE_LINE_POSITIVE: DATA_SERIES_TYPE_LINE_POSITIVE,
	DATA_SERIES_TYPE_LINE_NEGATIVE: DATA_SERIES_TYPE_LINE_NEGATIVE,
	DATA_SERIES_TYPE_SPLINE_POSITIVE: DATA_SERIES_TYPE_SPLINE_POSITIVE,
	DATA_SERIES_TYPE_SPLINE_NEGATIVE: DATA_SERIES_TYPE_SPLINE_NEGATIVE,
	DATA_SERIES_TYPE_OPTIONS: DATA_SERIES_TYPE_OPTIONS,
	DATA_SERIES_TYPES: DATA_SERIES_TYPES,
	DATA_SERIES_STACK_LAST: DATA_SERIES_STACK_LAST,
	DATA_SERIES_STACK_FIRST: DATA_SERIES_STACK_FIRST,
	DATA_SERIES_STACK_EVERY: DATA_SERIES_STACK_EVERY,
	DATA_SERIES_STACK_OPTIONS: DATA_SERIES_STACK_OPTIONS,
	DATA_SERIES_STACKS: DATA_SERIES_STACKS,
	DATA_SERIES_AXIS_Y: DATA_SERIES_AXIS_Y,
	DATA_SERIES_AXIS_Y2: DATA_SERIES_AXIS_Y2,
	DATA_SERIES_AXIS_OPTIONS: DATA_SERIES_AXIS_OPTIONS,
	DATA_SERIES_AXES: DATA_SERIES_AXES
};